In [110]:
import pandas as pd

In [111]:
survey=pd.read_csv(r"C:\pandas_docs (2)\pandas_docs\survey_results_public.csv")

In [112]:
sch=pd.read_csv(r"C:\pandas_docs (2)\pandas_docs\survey_results_schema.csv")

In [113]:
#sch=pd.set_option('display.max_columns',2)

In [114]:
survey

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

- Q2 set respondant columns as index

In [116]:
survey.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [117]:
survey=pd.read_csv(r"C:\pandas_docs (2)\pandas_docs\survey_results_public.csv",index_col='Respondent')

- Q3 read the first 100 devlprs personal info

In [119]:
survey

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [120]:
survey.loc[:100, ['Age','Gender','Hobbyist','Country','EdLevel','BetterLife','YearsCodePro']]

,Age,Gender,Hobbyist,Country,EdLevel,BetterLife,YearsCodePro
Respondent,,,,,,,
1,14.0,Man,Yes,United Kingdom,Primary/elementary school,Yes,NaN
2,19.0,Man,No,Bosnia and Herzegovina,"Secondary school (e.g. American high school, G...",Yes,NaN
3,28.0,Man,Yes,Thailand,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,1
4,22.0,Man,No,United States,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,Less than 1 year
5,30.0,Man,Yes,Ukraine,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,9
...,...,...,...,...,...,...,...
96,43.0,Man,No,Canada,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,19
97,25.0,"Non-binary, genderqueer, or gender non-conforming",Yes,United States,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,6
98,30.0,Man,Yes,Bosnia and Herzegovina,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Yes,NaN
99,21.0,Man,Yes,India,"Secondary school (e.g. American high school, G...",No,NaN
100,39.0,Woman,Yes,Canada,Some college/university study without earning ...,Yes,20

- Q4 1000th devlpr started his coding at the age

In [122]:
survey.loc[1000,'Age1stCode']

'10'

- Q5 most used social media of last devlpr in the df

In [124]:
survey.loc[88882,'SocialMedia']

'Instagram'

- Q6 100 to 200 devlprs salary and are they satisfied in their job ?

In [126]:
survey.loc[100:200,['JobSat','CompTotal']]

                                        JobSat  CompTotal
Respondent
100                             Very satisfied   300000.0
101                         Slightly satisfied        NaN
102                         Slightly satisfied    67800.0
103                                        NaN        NaN
104                          Very dissatisfied   155000.0
...                                        ...        ...
196                          Very dissatisfied    39000.0
197                      Slightly dissatisfied    86000.0
198                             Very satisfied        NaN
199                                        NaN        NaN
200         Neither satisfied nor dissatisfied        NaN

[100 rows x 2 columns]

- Q7 400 to 300 devlprs job satisfaction levle and what are challanges are they facing in thier working palce?

In [128]:
survey.loc[300:400,['JobSat','WorkChallenge']]

,JobSat,WorkChallenge
Respondent,,
300,NaN,NaN
301,Slightly satisfied,Distracting work environment;Not enough people...
302,Neither satisfied nor dissatisfied,Inadequate access to necessary tools;Lack of s...
303,Slightly dissatisfied,Distracting work environment;Meetings
304,Very satisfied,Not enough people for the workload
...,...,...
396,Very satisfied,"Non-work commitments (parenting, school work, ..."
397,NaN,NaN
398,Very satisfied,Being tasked with non-development work;Distrac...
399,Slightly dissatisfied,Inadequate access to necessary tools;Meetings;...
400,Very satisfied,Inadequate access to necessary tools

- Q8 how long devlpres 100,200,300 work in a week(by hours)

In [130]:
survey.loc[[100,200,300,]]['WorkWeekHrs']

Respondent
100    35.0
200    35.0
300     NaN
Name: WorkWeekHrs, dtype: float64

- Q9 salary of last 100 devlprs and their years of coding experience

In [132]:
survey.loc[88763:,'YearsCode']

Respondent
88763     31
88764      4
88765      2
88766      7
88767      5
        ...
88377    NaN
88601    NaN
88802    NaN
88816    NaN
88863      8
Name: YearsCode, Length: 670, dtype: object

- Q10 how many male and female devlprs are there in the last 100 devlpers

In [134]:
survey.loc[88763:,'Gender'].value_counts()

Gender
Man                                                            394
Woman                                                           66
Non-binary, genderqueer, or gender non-conforming               11
Woman;Man                                                        6
Man;Non-binary, genderqueer, or gender non-conforming            3
Woman;Non-binary, genderqueer, or gender non-conforming          2
Woman;Man;Non-binary, genderqueer, or gender non-conforming      1
Name: count, dtype: int64

-Q11 how many devlpers are there from india in the first 200 devlprs in list?

In [136]:
survey.loc[:200,'Country'].value_counts()

Country
United States             46
India                     20
United Kingdom            11
Germany                   11
Canada                     9
Australia                  6
Netherlands                5
Spain                      5
Russian Federation         5
South Africa               4
Austria                    4
Italy                      4
Argentina                  4
Poland                     4
New Zealand                4
Brazil                     3
France                     3
Sweden                     2
Bosnia and Herzegovina     2
Croatia                    2
Estonia                    2
Pakistan                   2
Ukraine                    2
China                      2
Greece                     2
Bangladesh                 2
Malaysia                   2
Czech Republic             2
Sri Lanka                  2
Turkey                     2
Switzerland                2
Hungary                    1
Viet Nam                   1
Finland                    1
Hong Kong (S.A.R.)         1
Bulgaria                   1
Iran                       1
Slovenia                   1
Belarus                    1
Latvia                     1
Romania                    1
Israel                     1
Ireland                    1
Japan                      1
South Korea                1
Thailand                   1
Azerbaijan                 1
Lithuania                  1
Philippines                1
Serbia                     1
Antigua and Barbuda        1
Denmark                    1
Colombia                   1
United Arab Emirates       1
Name: count, dtype: int64

-Q12 12.Developers whose agest 1st coded and current age from 4000 to 4500

In [138]:
survey.loc[4000:4500,['Age','Age1stCode']]

             Age Age1stCode
Respondent
4000        25.0         11
4001        28.0         14
4002        33.0         16
4003        17.0         10
4004        26.0         14
...          ...        ...
4496        18.0         15
4497        38.0         11
4498        27.0         20
4499        15.0         14
4500         NaN         20

[496 rows x 2 columns]

-Q13 Salary of 10000 to 11000 and are they have any dependents?

In [140]:
survey.loc[10000:11000,'Dependents']

Respondent
10000     No
10001    Yes
10002    Yes
10003     No
10004     No
        ...
10996    Yes
10997     No
10998    NaN
10999    Yes
11000     No
Name: Dependents, Length: 994, dtype: object

-Q14 salary of the developer 54 is really far from the salary of the 78th developer?

In [142]:
survey.loc[[54,78],'CompTotal']

Respondent
54     51500.0
78    550000.0
Name: CompTotal, dtype: float64

-Q15 How many unique Ethnicity are there in the devs community?

-Q15. How many unique Ethnicity are there in the devs community?

KeyError: 'Ethnicity'

In [ ]:
#b